CREATE TABLE IF NOT EXISTS USERS (
    USER_ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ITEM_ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100),
    AVAILABLE BOOL NOT NULL,
    OWNER_ID LONG NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

