CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ITEM_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100),
    AVAILABLE BOOLEAN NOT NULL,
    OWNER_ID BIGINT REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    BOOKING_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ITEM_ID BIGINT NOT NULL REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE,
    BOOKER_ID BIGINT NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    COMMENT_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TEXT VARCHAR NOT NULL,
    ITEM_ID BIGINT NOT NULL REFERENCES ITEMS(ITEM_ID),
    AUTHOR_ID BIGINT NOT NULL REFERENCES USERS(USER_ID),
    CREATED_DATE TIMESTAMP
);